/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    lineHeight: {
      'none': '1',
      'tight': '0.8',
      'snug': '1.2',
      'normal': '1.2',
      'relaxed': '1.2',
      'loose': '1.2',
      '3': '1.2',
      '4': '1.2',
      '5': '1.2',
      '6': '1.2',
      '7': '1.2',
      '8': '1.2',
      '9': '1.2',
      '10': '1.2',
    },
    colors: {
      black: 'hsl(var(--black) / 100%)',
      white: 'hsl(var(--white) / 100%)',
      ['transparent']: 'transparent',
      ['white']: 'hsla(var(--white) / 100%)',
      ['basic-gray-5']: 'hsla(var(--basic-gray-5) / var( --color-opacity-100))',
      ['basic-gray-10']: 'hsla(var(--basic-gray-10) / var( --color-opacity-100))',
      ['basic-gray-20']: 'hsla(var(--basic-gray-20) / var( --color-opacity-100))',
      ['basic-gray-30']: 'hsla(var(--basic-gray-30) / var( --color-opacity-100))',
      ['basic-gray-40']: 'hsla(var(--basic-gray-40) / var( --color-opacity-100))',
      ['basic-gray-50']: 'hsla(var(--basic-gray-50) / var( --color-opacity-100))',
      ['basic-gray-60']: 'hsla(var(--basic-gray-60) / var( --color-opacity-100))',
      ['basic-gray-80']: 'hsla(var(--basic-gray-80) / var( --color-opacity-100))',
      ['basic-gray-90']: 'hsla(var(--basic-gray-90) / var( --color-opacity-100))',

      ['gray-5']: 'hsla(var(--gray-5) / var( --color-opacity-100))',
      ['gray-10']: 'hsla(var(--gray-10) / var( --color-opacity-100))',
      ['gray-20']: 'hsla(var(--gray-20) / var( --color-opacity-100))',
      ['gray-30']: 'hsla(var(--gray-30) / var( --color-opacity-100))',
      ['gray-40']: 'hsla(var(--gray-40) / var( --color-opacity-100))',
      ['gray-50']: 'hsla(var(--gray-50) / var( --color-opacity-100))',
      ['gray-60']: 'hsla(var(--gray-60) / var( --color-opacity-100))',
      ['gray-70']: 'hsla(var(--gray-70) / var( --color-opacity-100))',
      ['gray-80']: 'hsla(var(--gray-80) / var( --color-opacity-100))',
      ['gray-90']: 'hsla(var(--gray-90) / var( --color-opacity-100))',
      ['gray-95']: 'hsla(var(--gray-95) / var( --color-opacity-100))',
      ['gray-100']: 'hsla(var(--gray-100) / var( --color-opacity-100))',

      ['blue-5']: 'hsla(var(--blue-5) / var( --color-opacity-100))',
      ['blue-10']: 'hsla(var(--blue-10) / var( --color-opacity-100))',
      ['blue-20']: 'hsla(var(--blue-20) / var( --color-opacity-100))',
      ['blue-30']: 'hsla(var(--blue-30) / var( --color-opacity-100))',
      ['blue-40']: 'hsla(var(--blue-40) / var( --color-opacity-100))',
      ['blue-50']: 'hsla(var(--blue-50) / var( --color-opacity-100))',
      ['blue-60']: 'hsla(var(--blue-60) / var( --color-opacity-100))',
      ['blue-70']: 'hsla(var(--blue-70) / var( --color-opacity-100))',
      ['blue-80']: 'hsla(var(--blue-80) / var( --color-opacity-100))',
      ['blue-90']: 'hsla(var(--blue-90) / var( --color-opacity-100))',
      ['blue-95']: 'hsla(var(--blue-95) / var( --color-opacity-100))',
      ['blue-100']: 'hsla(var(--blue-100) / var( --color-opacity-100))',

      ['red-5']: 'hsla(var(--red-5) / var( --color-opacity-100))',
      ['red-10']: 'hsla(var(--red-10) / var( --color-opacity-100))',
      ['red-20']: 'hsla(var(--red-20) / var( --color-opacity-100))',
      ['red-30']: 'hsla(var(--red-30) / var( --color-opacity-100))',
      ['red-40']: 'hsla(var(--red-40) / var( --color-opacity-100))',
      ['red-50']: 'hsla(var(--red-50) / var( --color-opacity-100))',
      ['red-60']: 'hsla(var(--red-60) / var( --color-opacity-100))',
      ['red-70']: 'hsla(var(--red-70) / var( --color-opacity-100))',
      ['red-80']: 'hsla(var(--red-80) / var( --color-opacity-100))',
      ['red-90']: 'hsla(var(--red-90) / var( --color-opacity-100))',
      ['red-100']: 'hsla(var(--red-100) / var( --color-opacity-100))',

      ['green-10']: 'hsla(var(--green-10) / var( --color-opacity-100))',
      ['green-20']: 'hsla(var(--green-20) / var( --color-opacity-100))',
      ['green-30']: 'hsla(var(--green-30) / var( --color-opacity-100))',
      ['green-40']: 'hsla(var(--green-40) / var( --color-opacity-100))',
      ['green-50']: 'hsla(var(--green-50) / var( --color-opacity-100))',
      ['green-60']: 'hsla(var(--green-60) / var( --color-opacity-100))',
      ['green-70']: 'hsla(var(--green-70) / var( --color-opacity-100))',
      ['green-80']: 'hsla(var(--green-80) / var( --color-opacity-100))',
      ['green-90']: 'hsla(var(--green-90) / var( --color-opacity-100))',
      ['green-100']: 'hsla(var(--green-100) / var( --color-opacity-100))',

      ['yellow-10']: 'hsla(var(--yellow-10) / var( --color-opacity-100))',
      ['yellow-20']: 'hsla(var(--yellow-20) / var( --color-opacity-100))',
      ['yellow-30']: 'hsla(var(--yellow-30) / var( --color-opacity-100))',
      ['yellow-40']: 'hsla(var(--yellow-40) / var( --color-opacity-100))',
      ['yellow-50']: 'hsla(var(--yellow-50) / var( --color-opacity-100))',
      ['yellow-60']: 'hsla(var(--yellow-60) / var( --color-opacity-100))',
      ['yellow-70']: 'hsla(var(--yellow-70) / var( --color-opacity-100))',
      ['yellow-80']: 'hsla(var(--yellow-80) / var( --color-opacity-100))',
      ['yellow-90']: 'hsla(var(--yellow-90) / var( --color-opacity-100))',
      ['yellow-100']: 'hsla(var(--yellow-100) / var( --color-opacity-100))',

      ['lime-10']: 'hsla(var(--lime-10) / var( --color-opacity-100))',
      ['lime-20']: 'hsla(var(--lime-20) / var( --color-opacity-100))',
      ['lime-30']: 'hsla(var(--lime-30) / var( --color-opacity-100))',
      ['lime-40']: 'hsla(var(--lime-40) / var( --color-opacity-100))',
      ['lime-50']: 'hsla(var(--lime-50) / var( --color-opacity-100))',
      ['lime-60']: 'hsla(var(--lime-60) / var( --color-opacity-100))',
      ['lime-70']: 'hsla(var(--lime-70) / var( --color-opacity-100))',
      ['lime-80']: 'hsla(var(--lime-80) / var( --color-opacity-100))',
      ['lime-90']: 'hsla(var(--lime-90) / var( --color-opacity-100))',
      ['lime-100']: 'hsla(var(--lime-100) / var( --color-opacity-100))',

      ['cyan-10']: 'hsla(var(--cyan-10) / var( --color-opacity-100))',
      ['cyan-20']: 'hsla(var(--cyan-20) / var( --color-opacity-100))',
      ['cyan-30']: 'hsla(var(--cyan-30) / var( --color-opacity-100))',
      ['cyan-40']: 'hsla(var(--cyan-40) / var( --color-opacity-100))',
      ['cyan-50']: 'hsla(var(--cyan-50) / var( --color-opacity-100))',
      ['cyan-60']: 'hsla(var(--cyan-60) / var( --color-opacity-100))',
      ['cyan-70']: 'hsla(var(--cyan-70) / var( --color-opacity-100))',
      ['cyan-80']: 'hsla(var(--cyan-80) / var( --color-opacity-100))',
      ['cyan-90']: 'hsla(var(--cyan-90) / var( --color-opacity-100))',
      ['cyan-100']: 'hsla(var(--cyan-100) / var( --color-opacity-100))',

      ['purple-10']: 'hsla(var(--purple-10) / var( --color-opacity-100))',
      ['purple-20']: 'hsla(var(--purple-20) / var( --color-opacity-100))',
      ['purple-30']: 'hsla(var(--purple-30) / var( --color-opacity-100))',
      ['purple-40']: 'hsla(var(--purple-40) / var( --color-opacity-100))',
      ['purple-50']: 'hsla(var(--purple-50) / var( --color-opacity-100))',
      ['purple-60']: 'hsla(var(--purple-60) / var( --color-opacity-100))',
      ['purple-70']: 'hsla(var(--purple-70) / var( --color-opacity-100))',
      ['purple-80']: 'hsla(var(--purple-80) / var( --color-opacity-100))',
      ['purple-90']: 'hsla(var(--purple-90) / var( --color-opacity-100))',
      ['purple-100']: 'hsla(var(--purple-100) / var( --color-opacity-100))',

      ['pink-10']: 'hsla(var(--pink-10) / var( --color-opacity-100))',
      ['pink-20']: 'hsla(var(--pink-20) / var( --color-opacity-100))',
      ['pink-30']: 'hsla(var(--pink-30) / var( --color-opacity-100))',
      ['pink-40']: 'hsla(var(--pink-40) / var( --color-opacity-100))',
      ['pink-50']: 'hsla(var(--pink-50) / var( --color-opacity-100))',
      ['pink-60']: 'hsla(var(--pink-60) / var( --color-opacity-100))',
      ['pink-70']: 'hsla(var(--pink-70) / var( --color-opacity-100))',
      ['pink-80']: 'hsla(var(--pink-80) / var( --color-opacity-100))',
      ['pink-90']: 'hsla(var(--pink-90) / var( --color-opacity-100))',
      ['pink-100']:'hsla(var(--pink-100) / var( --color-opacity-100))',

    },
    extend: {
    },
  },
  plugins: [],
}

